_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"

avocode_upload_route:
    pattern: /admin/upload/media
    requirements:
        _method: POST

AcmeDemoBundle_admin_acme_demo_bundle_Library:
    resource: "@AcmeDemoBundle/Controller/Library/"
    type:     admingenerator
    prefix:   /admin/acme_demo_bundle/Library

AcmeDemoBundle_admin_acme_demo_bundle_Product:
    resource: "@AcmeDemoBundle/Controller/Product/"
    type:     admingenerator
    prefix:   /admin/acme_demo_bundle/Product

